apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: #these r replicaset labels, not pod labels
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector: #these r used to select the pods to create replicaset, these r not pod labels
    matchLabels:
      app: nginx
      tier: frontend
  #this is pod definition, this is used to create pods, these r not replicaset labels
  template:
    metadata:
      labels: #these r pod labels, not replicaset labels
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
